name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - ""               # default features only
          - "--all-features" # all features enabled

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose ${{ matrix.features }}
      - name: Run tests
        run: cargo test --verbose ${{ matrix.features }}
